"""
export_best_bets.py
-------------------
Reads today's predictions from the nfl-predictions pipeline outputs and writes
a standardised best_bets_today.json to data_files/ for consumption by the
betting-oracle-dashboard aggregator.

Run manually:
    python export_best_bets.py

Run as part of the nightly GitHub Action (add to nightly-update.yml):
    - name: Export best bets for dashboard
      run: python export_best_bets.py

Output: data_files/best_bets_today.json

PORTING TO OTHER REPOS (hockey-predictions, golf-predictions):
    1. Update SPORT constant
    2. Update PREDICTIONS_FILE path if different
    3. Update COLUMN_MAP to match that repo's actual column names
    4. For golf: see the "Golf / Tournament Sports" section at the bottom
       and swap in the tournament-aware logic
"""

import json
import os
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

import pandas as pd

# ---------------------------------------------------------------------------
# Configuration — edit these when porting to another sport repo
# ---------------------------------------------------------------------------

SPORT = "NFL"

# Path to the predictions CSV generated by build_and_train_pipeline.py
# The README references this file being written by the pipeline.
# Adjust if your pipeline writes to a different name/location.
PREDICTIONS_FILE = Path("data_files/nfl_predictions.csv")

# Fallback: the betting recommendations log (already committed nightly)
# Used if PREDICTIONS_FILE doesn't exist or has no upcoming games.
BETTING_LOG_FILE = Path("data_files/betting_recommendations_log.csv")

# Output location consumed by the dashboard aggregator
OUTPUT_FILE = Path("data_files/best_bets_today.json")

# How many days ahead to include (0 = today only, 1 = today + tomorrow, etc.)
# NFL: 0 is usually right since games are weekly.
# NHL: 0 is right (daily games).
# Golf: set to 6 to cover a full tournament week.
LOOKAHEAD_DAYS = 0

# Minimum confidence tier to include in the export.
# Options (from the NFL repo's tier system): "Elite", "Strong", "Good", "Standard"
# Recommended: "Good" or higher to keep the dashboard signal-to-noise ratio high.
MIN_TIER = "Good"

# Maximum number of bets to export per sport per day.
# Keeps the dashboard digestible. Increase if you want more picks shown.
MAX_BETS = 10

# ---------------------------------------------------------------------------
# Column map — maps the pipeline's CSV columns → the unified dashboard schema
#
# IMPORTANT FOR PORTING: These column names come from the NFL repo's README
# and predictions.py. If your other repos use different column names, update
# this map. Any key that maps to None means "we'll derive it in code below."
# ---------------------------------------------------------------------------

COLUMN_MAP = {
    # Dashboard field        : CSV column name (or None if derived)
    "game_date"             : "gameday",           # e.g. "2025-09-14"
    "game_time"             : "gametime",          # e.g. "20:20" — may not exist, None fallback
    "home_team"             : "home_team",
    "away_team"             : "away_team",
    "spread_line"           : "spread_line",       # e.g. -3.5 (negative = home is favourite)
    "over_under_line"       : "total_line",        # total points line
    "moneyline_home"        : "home_moneyline",    # e.g. -180
    "moneyline_away"        : "away_moneyline",    # e.g. +155

    # Model outputs — from the NFL pipeline
    "prob_spread"           : "prob_underdogCovered",  # probability underdog covers spread
    "prob_moneyline"        : "prob_underdogWon",      # probability underdog wins outright
    "prob_over"             : "prob_overHit",           # probability over hits

    # Edge columns (model prob - implied prob). May not exist in all repos.
    "edge_spread"           : "spread_edge",       # derive if missing: prob_spread - implied
    "edge_moneyline"        : "ml_edge",
    "edge_over"             : "over_edge",

    # Tier assigned by the pipeline (Elite/Strong/Good/Standard)
    # The NFL repo calculates these in predictions.py — they may or may not
    # be written to the CSV. If missing, we derive them from confidence below.
    "tier"                  : "confidence_tier",   # may not exist in CSV

    # Optional: which model produced this row
    "model_path"            : "model_path",        # e.g. "analytics_blend" in NHL repo
}

# Tier thresholds — used when the CSV doesn't include a pre-computed tier.
# These match the NFL repo's logic (≥65% = Elite, 60-65% = Strong, etc.)
TIER_THRESHOLDS = {
    "Elite":    0.65,
    "Strong":   0.60,
    "Good":     0.55,
    "Standard": 0.00,
}

TIER_ORDER = ["Elite", "Strong", "Good", "Standard"]


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def get_col(df: pd.DataFrame, col_name: str):
    """Return a series if the column exists, else a Series of None."""
    return df[col_name] if col_name in df.columns else pd.Series([None] * len(df))


def moneyline_to_implied_prob(ml) -> float:
    """Convert American moneyline odds to implied probability (0–1)."""
    try:
        ml = float(ml)
        if ml > 0:
            return 100 / (ml + 100)
        elif ml < 0:
            return abs(ml) / (abs(ml) + 100)
    except (TypeError, ValueError):
        pass
    return None


def assign_tier(confidence: float) -> str:
    """Assign a tier label based on confidence probability."""
    if confidence is None:
        return "Standard"
    for tier in TIER_ORDER:
        if confidence >= TIER_THRESHOLDS[tier]:
            return tier
    return "Standard"


def tier_passes_minimum(tier: str, min_tier: str) -> bool:
    """Return True if tier is >= min_tier in the ordering Elite > Strong > Good > Standard."""
    return TIER_ORDER.index(tier) <= TIER_ORDER.index(min_tier)


def build_game_label(away: str, home: str) -> str:
    return f"{away} @ {home}" if away and home else "Unknown Matchup"


def build_pick_label(bet_type: str, row: dict) -> str:
    """
    Build a human-readable pick string, e.g. "Raiders +3.5" or "OVER 47.5".
    This is intentionally simple — the dashboard can reformat as needed.
    """
    if bet_type == "Spread":
        underdog = row.get("_underdog", "")
        spread = row.get("spread_line")
        if underdog and spread is not None:
            # If spread_line is negative, home is the favourite; underdog gets positive spread
            underdog_spread = abs(float(spread))
            return f"{underdog} +{underdog_spread}"
        return "Underdog covers"

    elif bet_type == "Moneyline":
        underdog = row.get("_underdog", "")
        ml = row.get("_underdog_ml", "")
        if underdog:
            ml_str = f" ({'+' if ml and float(ml) > 0 else ''}{ml})" if ml else ""
            return f"{underdog} ML{ml_str}"
        return "Underdog ML"

    elif bet_type == "Over/Under":
        line = row.get("over_under_line", "")
        direction = row.get("_over_under_direction", "OVER")
        return f"{direction} {line}" if line else direction

    return bet_type


# ---------------------------------------------------------------------------
# Core extraction logic
# ---------------------------------------------------------------------------

def load_predictions(filepath: Path) -> pd.DataFrame:
    """Load the predictions CSV, trying common encodings."""
    if not filepath.exists():
        print(f"  [WARN] {filepath} not found, skipping.")
        return pd.DataFrame()
    try:
        df = pd.read_csv(filepath, low_memory=False)
        print(f"  [OK] Loaded {len(df)} rows from {filepath}")
        return df
    except Exception as e:
        print(f"  [ERROR] Could not read {filepath}: {e}")
        return pd.DataFrame()


def filter_date_window(df: pd.DataFrame, date_col: str, lookahead: int) -> pd.DataFrame:
    """Keep only rows within today → today + lookahead_days."""
    if date_col not in df.columns:
        print(f"  [WARN] Date column '{date_col}' not found. Returning all rows.")
        return df

    today = datetime.now(timezone.utc).date()
    cutoff = today + timedelta(days=lookahead)

    df[date_col] = pd.to_datetime(df[date_col], errors="coerce").dt.date
    mask = (df[date_col] >= today) & (df[date_col] <= cutoff)
    filtered = df[mask].copy()
    print(f"  [OK] {len(filtered)} rows in date window {today} → {cutoff}")
    return filtered


def extract_bets(df: pd.DataFrame) -> list[dict]:
    """
    Iterate over prediction rows and emit one dict per qualifying bet.
    A single game row can produce up to 3 bets (Spread, Moneyline, Over/Under).
    """
    bets = []

    date_col      = COLUMN_MAP["game_date"]
    time_col      = COLUMN_MAP["game_time"]
    home_col      = COLUMN_MAP["home_team"]
    away_col      = COLUMN_MAP["away_team"]
    spread_col    = COLUMN_MAP["spread_line"]
    ou_col        = COLUMN_MAP["over_under_line"]
    ml_home_col   = COLUMN_MAP["moneyline_home"]
    ml_away_col   = COLUMN_MAP["moneyline_away"]
    prob_sp_col   = COLUMN_MAP["prob_spread"]
    prob_ml_col   = COLUMN_MAP["prob_moneyline"]
    prob_ov_col   = COLUMN_MAP["prob_over"]
    edge_sp_col   = COLUMN_MAP["edge_spread"]
    edge_ml_col   = COLUMN_MAP["edge_moneyline"]
    edge_ov_col   = COLUMN_MAP["edge_over"]
    tier_col      = COLUMN_MAP["tier"]
    model_col     = COLUMN_MAP["model_path"]

    for _, row in df.iterrows():
        home      = row.get(home_col, "")
        away      = row.get(away_col, "")
        game_date = str(row.get(date_col, ""))
        game_time = row.get(time_col, None)
        spread    = row.get(spread_col, None)
        ou_line   = row.get(ou_col, None)
        ml_home   = row.get(ml_home_col, None)
        ml_away   = row.get(ml_away_col, None)
        model     = row.get(model_col, "XGBoost")

        # Determine underdog (the team getting points, i.e. spread_line > 0 for away)
        # NFL repo convention: spread_line is from home team perspective
        # negative spread_line = home is favourite, away is underdog
        try:
            spread_val = float(spread)
            if spread_val < 0:
                underdog, favourite   = away, home
                underdog_ml, fav_ml  = ml_away, ml_home
            else:
                underdog, favourite   = home, away
                underdog_ml, fav_ml  = ml_home, ml_away
        except (TypeError, ValueError):
            underdog, favourite   = away, home
            underdog_ml, fav_ml  = ml_away, ml_home
            spread_val = None

        base = {
            "sport"       : SPORT,
            "game"        : build_game_label(away, home),
            "home_team"   : home,
            "away_team"   : away,
            "game_date"   : game_date,
            "game_time"   : str(game_time) if game_time else None,
            "spread_line" : spread_val,
            "over_under_line": float(ou_line) if ou_line else None,
            "model"       : model,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            # Internal helpers used by build_pick_label — not written to JSON
            "_underdog"   : underdog,
            "_underdog_ml": underdog_ml,
        }

        # ── Spread bet ──────────────────────────────────────────────────────
        prob_sp = row.get(prob_sp_col)
        if pd.notna(prob_sp) and prob_sp is not None:
            prob_sp = float(prob_sp)

            # Edge: use pre-computed column if available, else derive
            edge_sp = row.get(edge_sp_col)
            if pd.isna(edge_sp) or edge_sp is None:
                impl = moneyline_to_implied_prob(underdog_ml)
                edge_sp = round(prob_sp - impl, 4) if impl else None
            else:
                edge_sp = round(float(edge_sp), 4)

            # Tier: use pre-computed or assign from confidence
            tier_raw = row.get(tier_col)
            tier = str(tier_raw) if tier_raw and not pd.isna(tier_raw) else assign_tier(prob_sp)

            if tier_passes_minimum(tier, MIN_TIER):
                bet = {**base,
                    "bet_type"  : "Spread",
                    "pick"      : build_pick_label("Spread", base),
                    "confidence": round(prob_sp, 4),
                    "edge"      : edge_sp,
                    "tier"      : tier,
                }
                bet.pop("_underdog", None)
                bet.pop("_underdog_ml", None)
                bets.append(bet)

        # ── Moneyline bet ───────────────────────────────────────────────────
        prob_ml = row.get(prob_ml_col)
        if pd.notna(prob_ml) and prob_ml is not None:
            prob_ml = float(prob_ml)

            edge_ml = row.get(edge_ml_col)
            if pd.isna(edge_ml) or edge_ml is None:
                impl = moneyline_to_implied_prob(underdog_ml)
                edge_ml = round(prob_ml - impl, 4) if impl else None
            else:
                edge_ml = round(float(edge_ml), 4)

            tier_raw = row.get(tier_col)
            tier = str(tier_raw) if tier_raw and not pd.isna(tier_raw) else assign_tier(prob_ml)

            if tier_passes_minimum(tier, MIN_TIER):
                bet = {**base,
                    "bet_type"  : "Moneyline",
                    "pick"      : build_pick_label("Moneyline", base),
                    "confidence": round(prob_ml, 4),
                    "edge"      : edge_ml,
                    "tier"      : tier,
                }
                bet.pop("_underdog", None)
                bet.pop("_underdog_ml", None)
                bets.append(bet)

        # ── Over/Under bet ──────────────────────────────────────────────────
        prob_ov = row.get(prob_ov_col)
        if pd.notna(prob_ov) and prob_ov is not None:
            prob_ov = float(prob_ov)
            direction = "OVER" if prob_ov >= 0.5 else "UNDER"
            # Normalise: confidence is always the prob of whichever side we're picking
            confidence_ov = prob_ov if direction == "OVER" else 1 - prob_ov

            edge_ov = row.get(edge_ov_col)
            if pd.isna(edge_ov) or edge_ov is None:
                edge_ov = None
            else:
                edge_ov = round(float(edge_ov), 4)

            tier_raw = row.get(tier_col)
            tier = str(tier_raw) if tier_raw and not pd.isna(tier_raw) else assign_tier(confidence_ov)

            if tier_passes_minimum(tier, MIN_TIER):
                base_ou = {**base, "_over_under_direction": direction}
                bet = {**base_ou,
                    "bet_type"  : "Over/Under",
                    "pick"      : build_pick_label("Over/Under", base_ou),
                    "confidence": round(confidence_ov, 4),
                    "edge"      : edge_ov,
                    "tier"      : tier,
                }
                bet.pop("_underdog", None)
                bet.pop("_underdog_ml", None)
                bet.pop("_over_under_direction", None)
                bets.append(bet)

    return bets


def rank_and_trim(bets: list[dict], max_bets: int) -> list[dict]:
    """
    Sort by tier (Elite first) then by confidence descending.
    Trim to max_bets.
    """
    tier_rank = {t: i for i, t in enumerate(TIER_ORDER)}
    bets.sort(key=lambda b: (tier_rank.get(b.get("tier", "Standard"), 99),
                              -b.get("confidence", 0)))
    return bets[:max_bets]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print(f"\n{'='*60}")
    print(f"  export_best_bets.py — Sport: {SPORT}")
    print(f"  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"{'='*60}\n")

    # Try primary predictions file first
    df = load_predictions(PREDICTIONS_FILE)

    # Fall back to betting log if primary is empty or missing
    if df.empty:
        print(f"  Falling back to {BETTING_LOG_FILE}")
        df = load_predictions(BETTING_LOG_FILE)

    if df.empty:
        print("\n  [WARN] No prediction data found. Writing empty JSON.")
        OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_FILE.write_text(json.dumps([], indent=2))
        print(f"  [OK] Wrote empty array to {OUTPUT_FILE}")
        sys.exit(0)

    # Narrow to the date window
    date_col = COLUMN_MAP["game_date"]
    df = filter_date_window(df, date_col, LOOKAHEAD_DAYS)

    if df.empty:
        print(f"\n  [INFO] No games in the next {LOOKAHEAD_DAYS + 1} day(s). Writing empty JSON.")
        OUTPUT_FILE.write_text(json.dumps([], indent=2))
        print(f"  [OK] Wrote empty array to {OUTPUT_FILE}")
        sys.exit(0)

    # Extract individual bets from each game row
    print(f"\n  Extracting bets (min tier: {MIN_TIER}, max: {MAX_BETS})...")
    bets = extract_bets(df)
    print(f"  [OK] {len(bets)} qualifying bets found before trimming")

    # Rank and trim
    bets = rank_and_trim(bets, MAX_BETS)
    print(f"  [OK] {len(bets)} bets after ranking and trimming to top {MAX_BETS}")

    # Write output
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(json.dumps(bets, indent=2, default=str))
    print(f"\n  [OK] Written to {OUTPUT_FILE}")

    # Print summary to stdout (visible in GitHub Actions logs)
    print(f"\n  {'─'*40}")
    print(f"  Today's Best Bets ({SPORT})")
    print(f"  {'─'*40}")
    for b in bets:
        tier_icon = {"Elite": "🔥", "Strong": "⭐", "Good": "📈"}.get(b["tier"], "")
        print(f"  {tier_icon} [{b['tier']}] {b['game']} | {b['bet_type']} | {b['pick']} | conf: {b['confidence']:.1%}")
    print()


# ---------------------------------------------------------------------------
# Golf / Tournament Sports — paste this block into golf-predictions repo
# and replace the main() call above with main_tournament()
# ---------------------------------------------------------------------------
#
# def main_tournament():
#     """
#     Golf variant: predictions cover a full tournament week, not a single day.
#     The schema adds 'tournament_name' and uses broader bet types.
#     LOOKAHEAD_DAYS should be set to 6 when porting.
#     """
#     # TODO: load golf predictions parquet/csv
#     # df = pd.read_parquet("data_files/tournament_predictions.parquet")
#     #
#     # Golf-specific fields to add to each bet dict:
#     # {
#     #   "sport": "PGA",
#     #   "tournament_name": "The Masters",
#     #   "tournament_start": "2025-04-10",
#     #   "tournament_end": "2025-04-13",
#     #   "player": "Scottie Scheffler",
#     #   "bet_type": "Top 10",        # Outright Win / Top 5 / Top 10 / Make Cut
#     #   "pick": "Scottie Scheffler Top 10",
#     #   "confidence": 0.71,
#     #   "world_ranking": 1,
#     #   "course_fit_score": 0.84,    # if your model has this
#     #   "edge": 0.09,
#     #   "tier": "Elite",
#     #   "model": "XGBoost",
#     #   "generated_at": "..."
#     # }
#     pass


if __name__ == "__main__":
    main()
